/**
 * Sample dividend holdings for demonstration.
 * Replace with real data from PocketBase once imported.
 */

import type { DividendStockData } from './qualityScoring';

export const SAMPLE_HOLDINGS: DividendStockData[] = [
  {
    symbol: 'JNJ',
    name: 'Johnson & Johnson',
    currentYield: 3.2,
    fiveYearAvgYield: 2.7,
    dividendGrowthRate: 6.0,
    peRatio: 15.8,
    priceVs52WeekHigh: 12,
    payoutRatio: 45,
    isDividendKing: true,
    isDividendAristocrat: true,
    paymentMonth: 3,
    calendarGroup: 'A',
    annualDividendPerShare: 4.96,
    sharesHeld: 25,
    costBasis: 3750,
  },
  {
    symbol: 'PEP',
    name: 'PepsiCo',
    currentYield: 3.5,
    fiveYearAvgYield: 2.9,
    dividendGrowthRate: 7.0,
    peRatio: 22.1,
    priceVs52WeekHigh: 18,
    payoutRatio: 65,
    isDividendKing: false,
    isDividendAristocrat: true,
    paymentMonth: 1,
    calendarGroup: 'B',
    annualDividendPerShare: 5.42,
    sharesHeld: 20,
    costBasis: 3100,
  },
  {
    symbol: 'ABBV',
    name: 'AbbVie',
    currentYield: 3.8,
    fiveYearAvgYield: 4.2,
    dividendGrowthRate: 8.5,
    peRatio: 13.5,
    priceVs52WeekHigh: 8,
    payoutRatio: 52,
    isDividendKing: false,
    isDividendAristocrat: true,
    paymentMonth: 2,
    calendarGroup: 'C',
    annualDividendPerShare: 6.56,
    sharesHeld: 30,
    costBasis: 5100,
  },
  {
    symbol: 'KO',
    name: 'Coca-Cola',
    currentYield: 3.1,
    fiveYearAvgYield: 3.0,
    dividendGrowthRate: 5.0,
    peRatio: 24.5,
    priceVs52WeekHigh: 5,
    payoutRatio: 72,
    isDividendKing: true,
    isDividendAristocrat: true,
    paymentMonth: 4,
    calendarGroup: 'B',
    annualDividendPerShare: 1.94,
    sharesHeld: 50,
    costBasis: 3100,
  },
  {
    symbol: 'PG',
    name: 'Procter & Gamble',
    currentYield: 2.5,
    fiveYearAvgYield: 2.4,
    dividendGrowthRate: 6.5,
    peRatio: 26.0,
    priceVs52WeekHigh: 7,
    payoutRatio: 60,
    isDividendKing: true,
    isDividendAristocrat: true,
    paymentMonth: 2,
    calendarGroup: 'C',
    annualDividendPerShare: 4.03,
    sharesHeld: 20,
    costBasis: 3200,
  },
  {
    symbol: 'O',
    name: 'Realty Income',
    currentYield: 5.5,
    fiveYearAvgYield: 4.5,
    dividendGrowthRate: 4.0,
    peRatio: 38.0,
    priceVs52WeekHigh: 22,
    payoutRatio: 80,
    isDividendKing: false,
    isDividendAristocrat: false,
    paymentMonth: 1,
    calendarGroup: 'B',
    annualDividendPerShare: 3.10,
    sharesHeld: 40,
    costBasis: 2240,
  },
  {
    symbol: 'VGT',
    name: 'Vanguard IT ETF',
    currentYield: 0.6,
    fiveYearAvgYield: 0.7,
    dividendGrowthRate: 12.0,
    peRatio: 30.0,
    priceVs52WeekHigh: 3,
    payoutRatio: 25,
    isDividendKing: false,
    isDividendAristocrat: false,
    paymentMonth: 3,
    calendarGroup: 'A',
    annualDividendPerShare: 3.50,
    sharesHeld: 15,
    costBasis: 7500,
  },
  {
    symbol: 'ADM',
    name: 'Archer-Daniels-Midland',
    currentYield: 3.9,
    fiveYearAvgYield: 2.8,
    dividendGrowthRate: 9.0,
    peRatio: 11.2,
    priceVs52WeekHigh: 35,
    payoutRatio: 40,
    isDividendKing: false,
    isDividendAristocrat: true,
    paymentMonth: 3,
    calendarGroup: 'A',
    annualDividendPerShare: 2.00,
    sharesHeld: 40,
    costBasis: 2040,
  },
];

export const SAMPLE_SETTINGS = {
  annualExpenses: 60000,
  monthlyContribution: 500,
  averageYield: 3.5,
};
