/**
 * SWAN Dividend Portfolio — Target Holdings (10-15 stocks)
 *
 * Selection criteria:
 * - Dividend Kings (50+ years) or Aristocrats (25+ years)
 * - Qualified dividends only (no REITs)
 * - Spread across 3 calendar groups for monthly income
 * - Max 10-15 concentrated positions
 *
 * Calendar Groups (by ex-dividend month pattern):
 * - Group A (Jan/Apr/Jul/Oct): PG, ABBV, ITW, MCD
 * - Group B (Feb/May/Aug/Nov): ADM, HRL, ED
 * - Group C (Mar/Jun/Sep/Dec): KO, KMB, NEE, JNJ, PEP
 */

import type { DividendStockData } from './qualityScoring';

/**
 * The target dividend portfolio — 11 stocks, all qualified dividends.
 * sharesHeld and costBasis will be overridden from PocketBase data.
 */
export const TARGET_PORTFOLIO: DividendStockData[] = [
  // ─── Group A (Jan/Apr/Jul/Oct) ───
  {
    symbol: 'PG',
    name: 'Procter & Gamble',
    currentYield: 2.4,
    fiveYearAvgYield: 2.4,
    dividendGrowthRate: 6.0,
    peRatio: 26.0,
    priceVs52WeekHigh: 7,
    payoutRatio: 60,
    isDividendKing: true,
    isDividendAristocrat: true,
    paymentMonth: 1,
    calendarGroup: 'A',
    annualDividendPerShare: 4.03,
    sharesHeld: 0,
    costBasis: 0,
  },
  {
    symbol: 'ABBV',
    name: 'AbbVie',
    currentYield: 3.6,
    fiveYearAvgYield: 4.0,
    dividendGrowthRate: 8.5,
    peRatio: 14.0,
    priceVs52WeekHigh: 8,
    payoutRatio: 48,
    isDividendKing: true,
    isDividendAristocrat: true,
    paymentMonth: 1,
    calendarGroup: 'A',
    annualDividendPerShare: 6.56,
    sharesHeld: 0,
    costBasis: 0,
  },
  {
    symbol: 'MCD',
    name: "McDonald's",
    currentYield: 2.2,
    fiveYearAvgYield: 2.2,
    dividendGrowthRate: 8.0,
    peRatio: 25.0,
    priceVs52WeekHigh: 5,
    payoutRatio: 55,
    isDividendKing: false, // King in 2026 (49 years)
    isDividendAristocrat: true,
    paymentMonth: 1,
    calendarGroup: 'A',
    annualDividendPerShare: 7.08,
    sharesHeld: 12.75,
    costBasis: 3295,
  },
  {
    symbol: 'ITW',
    name: 'Illinois Tool Works',
    currentYield: 2.3,
    fiveYearAvgYield: 2.1,
    dividendGrowthRate: 7.0,
    peRatio: 25.0,
    priceVs52WeekHigh: 12,
    payoutRatio: 55,
    isDividendKing: true,
    isDividendAristocrat: true,
    paymentMonth: 1,
    calendarGroup: 'A',
    annualDividendPerShare: 5.64,
    sharesHeld: 0,
    costBasis: 0,
  },
  {
    symbol: 'SWK',
    name: 'Stanley Black & Decker',
    currentYield: 4.0,
    fiveYearAvgYield: 2.5,
    dividendGrowthRate: 3.0,
    peRatio: 16.0,
    priceVs52WeekHigh: 35,
    payoutRatio: 70,
    isDividendKing: true,
    isDividendAristocrat: true,
    paymentMonth: 1,
    calendarGroup: 'A',
    annualDividendPerShare: 3.24,
    sharesHeld: 0,
    costBasis: 0,
  },
  // ─── Group B (Feb/May/Aug/Nov) ───
  {
    symbol: 'ADM',
    name: 'Archer-Daniels-Midland',
    currentYield: 3.5,
    fiveYearAvgYield: 2.8,
    dividendGrowthRate: 9.0,
    peRatio: 11.0,
    priceVs52WeekHigh: 35,
    payoutRatio: 38,
    isDividendKing: true,
    isDividendAristocrat: true,
    paymentMonth: 2,
    calendarGroup: 'B',
    annualDividendPerShare: 2.00,
    sharesHeld: 41.58,
    costBasis: 2519,
  },
  {
    symbol: 'HRL',
    name: 'Hormel Foods',
    currentYield: 3.8,
    fiveYearAvgYield: 2.5,
    dividendGrowthRate: 6.0,
    peRatio: 20.0,
    priceVs52WeekHigh: 30,
    payoutRatio: 65,
    isDividendKing: true,
    isDividendAristocrat: true,
    paymentMonth: 2,
    calendarGroup: 'B',
    annualDividendPerShare: 1.13,
    sharesHeld: 109.03,
    costBasis: 3430,
  },
  {
    symbol: 'ED',
    name: 'Consolidated Edison',
    currentYield: 3.4,
    fiveYearAvgYield: 3.5,
    dividendGrowthRate: 3.5,
    peRatio: 19.0,
    priceVs52WeekHigh: 10,
    payoutRatio: 62,
    isDividendKing: true,
    isDividendAristocrat: true,
    paymentMonth: 2,
    calendarGroup: 'B',
    annualDividendPerShare: 3.44,
    sharesHeld: 0,
    costBasis: 0,
  },
  {
    symbol: 'TGT',
    name: 'Target',
    currentYield: 4.5,
    fiveYearAvgYield: 2.8,
    dividendGrowthRate: 8.0,
    peRatio: 12.0,
    priceVs52WeekHigh: 40,
    payoutRatio: 52,
    isDividendKing: true,
    isDividendAristocrat: true,
    paymentMonth: 2,
    calendarGroup: 'B',
    annualDividendPerShare: 4.48,
    sharesHeld: 0,
    costBasis: 0,
  },
  {
    symbol: 'GPC',
    name: 'Genuine Parts',
    currentYield: 3.0,
    fiveYearAvgYield: 2.8,
    dividendGrowthRate: 6.0,
    peRatio: 16.0,
    priceVs52WeekHigh: 25,
    payoutRatio: 50,
    isDividendKing: true,
    isDividendAristocrat: true,
    paymentMonth: 2,
    calendarGroup: 'B',
    annualDividendPerShare: 4.00,
    sharesHeld: 0,
    costBasis: 0,
  },
  // ─── Group C (Mar/Jun/Sep/Dec) ───
  {
    symbol: 'KO',
    name: 'Coca-Cola',
    currentYield: 2.8,
    fiveYearAvgYield: 3.0,
    dividendGrowthRate: 5.0,
    peRatio: 24.0,
    priceVs52WeekHigh: 5,
    payoutRatio: 70,
    isDividendKing: true,
    isDividendAristocrat: true,
    paymentMonth: 3,
    calendarGroup: 'C',
    annualDividendPerShare: 1.94,
    sharesHeld: 4.85,
    costBasis: 293,
  },
  {
    symbol: 'KMB',
    name: 'Kimberly-Clark',
    currentYield: 3.6,
    fiveYearAvgYield: 3.4,
    dividendGrowthRate: 4.0,
    peRatio: 18.0,
    priceVs52WeekHigh: 15,
    payoutRatio: 65,
    isDividendKing: true,
    isDividendAristocrat: true,
    paymentMonth: 3,
    calendarGroup: 'C',
    annualDividendPerShare: 5.08,
    sharesHeld: 24.15,
    costBasis: 2793,
  },
  {
    symbol: 'NEE',
    name: 'NextEra Energy',
    currentYield: 2.9,
    fiveYearAvgYield: 2.2,
    dividendGrowthRate: 10.0,
    peRatio: 22.0,
    priceVs52WeekHigh: 12,
    payoutRatio: 60,
    isDividendKing: false,
    isDividendAristocrat: false, // Strong grower, not yet 25 years
    paymentMonth: 3,
    calendarGroup: 'C',
    annualDividendPerShare: 2.06,
    sharesHeld: 1.06,
    costBasis: 67,
  },
  {
    symbol: 'JNJ',
    name: 'Johnson & Johnson',
    currentYield: 3.2,
    fiveYearAvgYield: 2.7,
    dividendGrowthRate: 6.0,
    peRatio: 16.0,
    priceVs52WeekHigh: 10,
    payoutRatio: 45,
    isDividendKing: true,
    isDividendAristocrat: true,
    paymentMonth: 3,
    calendarGroup: 'C',
    annualDividendPerShare: 4.96,
    sharesHeld: 0,
    costBasis: 0,
  },
  {
    symbol: 'PEP',
    name: 'PepsiCo',
    currentYield: 3.5,
    fiveYearAvgYield: 2.9,
    dividendGrowthRate: 7.0,
    peRatio: 22.0,
    priceVs52WeekHigh: 18,
    payoutRatio: 65,
    isDividendKing: true,
    isDividendAristocrat: true,
    paymentMonth: 3,
    calendarGroup: 'C',
    annualDividendPerShare: 5.42,
    sharesHeld: 0,
    costBasis: 0,
  },
];

/**
 * Retirement/FI settings for the dividend portfolio
 */
export const DIVIDEND_SETTINGS = {
  annualExpenses: 60000, // target annual living expenses
  monthlyContribution: 500, // how much new money deployed each month
  averageYield: 3.2, // blended portfolio yield target
  targetPositions: 15, // max number of stocks (5 per group)
  maxSinglePosition: 15, // max % any one stock can be of dividend portfolio
};

// Legacy export for backwards compatibility
export const SAMPLE_HOLDINGS = TARGET_PORTFOLIO;
export const SAMPLE_SETTINGS = DIVIDEND_SETTINGS;
